# Generated by Django 2.0.9 on 2023-12-22 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domociliary_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocate_service',
            name='STAFF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domociliary_services.staff'),
        ),
    ]
