# Generated by Django 3.2.21 on 2024-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domociliary_services', '0002_auto_20231222_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
