# Generated by Django 3.2.21 on 2024-02-27 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domociliary_services', '0003_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='CUSTOMER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='domociliary_services.customer'),
            preserve_default=False,
        ),
    ]
